#默认端口
server:
  port: 8080
  endpoint:
    info:
      enabled: true

spring:
  #环境组
  profiles:
    #    active: @profile.active@
    active: dev
    group:
      "dev": dev
      "prod": prod
      "test": test

