#默认端口
server:
  port: 8081
  endpoint:
    info:
      enabled: true

spring:
  #  程序名
  application:
    name: springboot-base【生产环境】
  boot:
    admin:
      client:
        url: http://127.0.0.1:9999
        #springbootClient-是否启用
        enabled: false
        # springbootAdmin 服务端用户名密码
        username: admin
        password: 123456
  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.28.206:3306/spring?serverTimeZone=UTC
    username: root
    password: root

# SpringBootClient 打开客户端 Actuator 的监控
management:
  endpoints:
    web:
      exposure:
        # 开放所有端点
        include: "*"
  # 关闭redis 健康监视
  health:
    redis:
      enabled: false

#日志拆分
logging:
  level:
    root: info
    g1: debug
    g2: info
  group:
    g1: com.zjyun.springboot.controller,com.zjyun.springboot.service
    g2: com.zjyun.springboot.entity
  file:
    name: logs/server.log
  logback:
    rollingpolicy:
      max-file-size: 50MB
      file-name-pattern: logs/server.%d{yyyy-MM-dd}.%i.log